language: c  
os:
  - linux
  - osx

sudo: required
dist: trusty


cache:
  directories:
    - node_modules

env:
  - NODE_VERSION="7.4.0"

addons:
  apt:
    packages:
      - graphicsmagick
      - icnsutils
      - gcc-multilib
      - g++-multilib
      - bsdtar
      - rpm

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
       git clone https://github.com/creationix/nvm.git /tmp/.nvm;
       source /tmp/.nvm/nvm.sh;
    fi
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION
  - node --version
  - npm install electron
  - npm install bower
  - npm install electron-builder

install:
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  npm run compile:lin; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  npm run compile:mac; fi
  - find out

script:
  - echo "nothing to do"

deploy:
  - provider: releases
    api_key:
      secure: Th34E/cIC3LXfAaRKbgFT/rXGIAcxny5tJ4HyxSIWnF+GM67d8n76csAzwNKvF0ERLnET6zmdzlUdhwgX2orfJTPqh4A8IQCYUTa+H2DtabT1dOjOM4M3p2Ni/l80jbKiCZfgw3/sUIyCjm7PDNiO25/0YkhoBszCLYTwSeTShi0T8AzCAo3hHUFikaaEHkbVBsnTnQWPOZhAgAGukotXqizwEscz8o/zC0P0yvb5tPpHK2Mj9iX5wPOkzVpegQJ0RWYxl/9S8zwWEaJoGYIIlZhQ4Y09WW9nJG3hr1yoo9Vq+eME2p/B9YqWcOghCe1WbdLlZ7cosES2JSpjI+lSuu4F/Q/t5yZDh/ykV9YqYg1RQ99+rr/ugSkvrfrf4NiFDECztwgGnmCkxTYnA4MU5xlp+5JCpehqKROPj4V5zeBeBnhDmhdSzh8Vje0y9UbCGYPYkHvoEpgNhxLiYinZjsk0zsAwAyQpIYQiCSdHYrPk4ZFWaAWA/ev/hxW2szyP6R7/B8MPtsClEvsJ1H3TN94gWaZnhx3r053KLMLVH3MBxonTJ38otXzcdY67Jm5jEJgHokKPLfE1z4Ul+RkcC8SGcYD7Hjj73woUGABnGIherWg8jZ/RwbT2Yi1I4Jl4CgtgYpmPHX731W+LBbyHSL1Gw1dmHTCwBGrg4tlPCk=
    file:
      - out/Aidos-*-ia32.AppImage
      - out/Aidos-*-x86_64.AppImage
      - out/Aidos-*-ia32.tar.gz
      - out/Aidos-*.tar.gz
      - out/Aidos_*_amd64.deb
      - out/Aidos-*.rpm
      - out/Aidos-*-ia32.rpm
    skip_cleanup: true
    file_glob: true
    on:
      repo: AidosKuneen/aidos-wallet
      tags: true
      all_branches: true
      condition: "$TRAVIS_OS_NAME == linux"

  - provider: releases
    api_key:
      secure: Th34E/cIC3LXfAaRKbgFT/rXGIAcxny5tJ4HyxSIWnF+GM67d8n76csAzwNKvF0ERLnET6zmdzlUdhwgX2orfJTPqh4A8IQCYUTa+H2DtabT1dOjOM4M3p2Ni/l80jbKiCZfgw3/sUIyCjm7PDNiO25/0YkhoBszCLYTwSeTShi0T8AzCAo3hHUFikaaEHkbVBsnTnQWPOZhAgAGukotXqizwEscz8o/zC0P0yvb5tPpHK2Mj9iX5wPOkzVpegQJ0RWYxl/9S8zwWEaJoGYIIlZhQ4Y09WW9nJG3hr1yoo9Vq+eME2p/B9YqWcOghCe1WbdLlZ7cosES2JSpjI+lSuu4F/Q/t5yZDh/ykV9YqYg1RQ99+rr/ugSkvrfrf4NiFDECztwgGnmCkxTYnA4MU5xlp+5JCpehqKROPj4V5zeBeBnhDmhdSzh8Vje0y9UbCGYPYkHvoEpgNhxLiYinZjsk0zsAwAyQpIYQiCSdHYrPk4ZFWaAWA/ev/hxW2szyP6R7/B8MPtsClEvsJ1H3TN94gWaZnhx3r053KLMLVH3MBxonTJ38otXzcdY67Jm5jEJgHokKPLfE1z4Ul+RkcC8SGcYD7Hjj73woUGABnGIherWg8jZ/RwbT2Yi1I4Jl4CgtgYpmPHX731W+LBbyHSL1Gw1dmHTCwBGrg4tlPCk=
    file:
      - out/mac/Aidos Wallet-*.dmg
    skip_cleanup: true
    file_glob: true
    on:
      repo: AidosKuneen/aidos-wallet
      tags: true
      all_branches: true
      condition: "$TRAVIS_OS_NAME == osx"
