platform:
  - x64
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 7 x64
  - npm install electron
  - npm install bower
  - npm install electron-builder
  - npm install
  - cd ccurl
  - C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\gcc  pow_sse2.c -O3 -static -lpthread -msse2 -shared -o libccurl.dll
  - copy libccurl.dll win64\
  - del libccurl.dll
  - cd ..

build_script:
  - npm run compile:win
  - tree /f out

test: off

artifacts:

  # pushing a single file
   - path: out\*.exe

deploy:
  release: $(appveyor_repo_tag_name)
  description: ''
  provider: GitHub
  auth_token:
      secure: 3iQcaZ+ekUfV7qNqpOzlT1mY/pT4mhoNxxKsySYB643/Y6QWaPEEHqiOzHtQh+6k
  artifact: /.*\.exe/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
 
